package version

const CURRENT_BACKEND_VERSION = "0.26.0"
const CURRENT_FRONTEND_VERSION = "0.26.0"

const RELEASED_APP_VERSION = "2026.3.3"
const RELEASED_BACKEND_VERSION = "0.26.0"
const RELEASED_FRONTEND_VERSION = "0.26.0"
