package detections

import "strings"

func (Detect *Definitions) GetExtDefinition(ext string) (string, Definition) {
	if value, exists := Detect.Extensions[ext]; exists {
		return ext, value
	}
	return "", Detect.Default
}

func GetFileExtension(mime string) string {
	switch {
	case strings.HasPrefix(mime, "image/svg"):
		return ".svg" // Assuming you wanted a generic .img extension for images
	case strings.HasPrefix(mime, "image/"):
		return ".png" // Assuming you wanted a generic .img extension for images
	case strings.HasPrefix(mime, "audio/"):
		return ".mp3"
	case strings.Contains(mime, "video/"):
		return ".mp4"
	case strings.Contains(mime, "javascript"):
		return ".js"
	case strings.Contains(mime, "json"):
		return ".json"
	case strings.Contains(mime, "css"):
		return ".css"
	case strings.Contains(mime, "font"):
		return ".ttf"
	case strings.Contains(mime, "html"):
		return ".html"
	case strings.Contains(mime, "xml"):
		return ".xml"
	case strings.Contains(mime, "ocsp-response"):
		return ".ocsp-response"
	case strings.Contains(mime, "text"):
		return ".text"
	case strings.Contains(mime, "binary"):
		return ".binary"
	case strings.Contains(mime, "octet"):
		return ".octet"
	case strings.Contains(mime, "protobuf"):
		return ".protobuf"
	default:
		return ".others" // Generic extension for others
	}
}

func (Detect *Definitions) GetMimeDefinition(mime string) (string, Definition) {
	ext := GetFileExtension(mime)
	if value, exists := Detect.Extensions[ext]; exists {
		return mime, value
	}
	return "", Detect.Default
}

func (Detect *Definitions) GetPathDefinition(path string) (string, Definition) {

	for file, definition := range Detect.Files {
		if strings.HasSuffix(path, file) {
			return file, definition
		}

	}

	for key, definition := range Detect.Partials {
		if strings.Contains(path, key) {
			return key, definition
		}
	}

	for key, definition := range Detect.Partials {
		if strings.Contains(path, key) {
			return key, definition
		}

	}
	return "", Detect.Default
}

func New() *Definitions {
	return &Definitions{
		Default: Definition{"custom", "ignore"},
		Partials: map[string]Definition{
			"TODO":                         {"todo", "blue"},
			"Procfile":                     {"heroku", "purple"},
			"cmakelists.txt":               {"makefile", "blue"},
			"CMakeLists.txt":               {"makefile", "blue"},
			"CMAKELISTS.txt":               {"makefile", "blue"},
			"CMAKELISTS.TXT":               {"makefile", "blue"},
			"omakefile":                    {"makefile", "grey-light"},
			"OMakefile":                    {"makefile", "grey-light"},
			"OMAKEFILE":                    {"makefile", "grey-light"},
			"qmakefile":                    {"makefile", "purple"},
			"QMakefile":                    {"makefile", "purple"},
			"QMAKEFILE":                    {"makefile", "purple"},
			"makefile":                     {"makefile", "orange"},
			"Makefile":                     {"makefile", "orange"},
			"MAKEFILE":                     {"makefile", "orange"},
			"CONTRIBUTING":                 {"license", "red"},
			"COMPILING":                    {"license", "orange"},
			"COPYING":                      {"license", "yellow"},
			"LICENCE":                      {"license", "yellow"},
			"LICENSE":                      {"license", "yellow"},
			"gulpfile.js":                  {"gulp", "red"},
			"gulpfile":                     {"gulp", "red"},
			"Gulpfile":                     {"gulp", "red"},
			"GULPFILE":                     {"gulp", "red"},
			"docker-compose.override.yaml": {"docker", "pink"},
			"docker-compose.override.yml":  {"docker", "pink"},
			"docker-compose.yaml":          {"docker", "pink"},
			"docker-compose.yml":           {"docker", "pink"},
			"docker-healthcheck":           {"docker", "green"},
			".dockerignore":                {"docker", "grey"},
			"DOCKERFILE":                   {"docker", "blue"},
			"Dockerfile":                   {"docker", "blue"},
			"dockerfile":                   {"docker", "blue"},
			// "mix":                          {"hex", "red"},
			"jquery.js": {"jquery", "blue"},
			"/graphql":  {"graphql", "red"},
			"/oauth":    {"oauth", "purple"},
			"/api":      {"json", "red"},
			"/v1":       {"json", "red"},
			"/v2":       {"json", "red"},
			"/v3":       {"json", "red"},
			"/v4":       {"json", "red"},
			"/v5":       {"json", "red"},
			"/v6":       {"json", "red"},
			"/v7":       {"json", "red"},
			"/v8":       {"json", "red"},
		},
		Files: map[string]Definition{
			"karma.conf.js":           {"karma", "green"},
			"karma.conf.coffee":       {"karma", "green"},
			"README.md":               {"info", "blue"},
			"CHANGELOG.md":            {"clock", "blue"},
			"CHANGELOG":               {"clock", "blue"},
			"CHANGES.md":              {"clock", "blue"},
			"VERSION.md":              {"clock", "blue"},
			"VERSION":                 {"clock", "blue"},
			"mvnw":                    {"maven", "red"},
			"tsconfig.json":           {"tsconfig", "blue"},
			"swagger.json":            {"json", "green"},
			"swagger.yml":             {"json", "green"},
			"swagger.yaml":            {"json", "green"},
			"mime.types":              {"config", "grey-light"},
			"Jenkinsfile":             {"jenkins", "red"},
			"babel.config.js":         {"babel", "yellow"},
			"babel.config.json":       {"babel", "yellow"},
			"babel.config.cjs":        {"babel", "yellow"},
			"bower.json":              {"bower", "orange"},
			"bower.text":              {"text", "red"},
			"Bower.json":              {"bower", "orange"},
			"firebase.json":           {"firebase", "orange"},
			"geckodriver":             {"firefox", "orange"},
			"Gruntfile.js":            {"grunt", "orange"},
			"gruntfile.babel.js":      {"grunt", "orange"},
			"Gruntfile.babel.js":      {"grunt", "orange"},
			"gruntfile.js":            {"grunt", "orange"},
			"Gruntfile.coffee":        {"grunt", "orange"},
			"gruntfile.coffee":        {"grunt", "orange"},
			"ionic.config.json":       {"ionic", "blue"},
			"Ionic.config.json":       {"ionic", "blue"},
			"ionic.project":           {"ionic", "blue"},
			"Ionic.project":           {"ionic", "blue"},
			"platformio.ini":          {"platformio", "orange"},
			"rollup.config.js":        {"rollup", "red"},
			"sass-lint.yml":           {"sass", "pink"},
			"stylelint.config.js":     {"stylelint", "white"},
			"yarn.clean":              {"yarn", "blue"},
			"yarn.lock":               {"yarn", "blue"},
			"webpack.config.js":       {"webpack", "blue"},
			"webpack.config.build.js": {"webpack", "blue"},
			"webpack.common.js":       {"webpack", "blue"},
			"webpack.dev.js":          {"webpack", "blue"},
			"webpack.prod.js":         {"webpack", "blue"},
			"npm-debug.log":           {"npm_ignored", "ignore"},
		},
		Extensions: map[string]Definition{
			".bsl":               {"bsl", "red"},
			".mdo":               {"mdo", "red"},
			".asm":               {"asm", "red"},
			".s":                 {"asm", "red"},
			".c":                 {"c", "blue"},
			".h":                 {"c", "purple"},
			".m":                 {"c", "yellow"},
			".cs":                {"c-sharp", "blue"},
			".cshtml":            {"html", "blue"},
			".aspx":              {"html", "blue"},
			".ashx":              {"html", "blue"},
			".ascx":              {"html", "green"},
			".asax":              {"html", "yellow"},
			".master":            {"html", "yellow"},
			".cc":                {"cpp", "blue"},
			".cpp":               {"cpp", "blue"},
			".cxx":               {"cpp", "blue"},
			".c++":               {"cpp", "blue"},
			".hh":                {"cpp", "purple"},
			".hpp":               {"cpp", "purple"},
			".hxx":               {"cpp", "purple"},
			".h++":               {"cpp", "purple"},
			".mm":                {"cpp", "yellow"},
			".clj":               {"clojure", "green"},
			".cljs":              {"clojure", "green"},
			".cljc":              {"clojure", "green"},
			".edn":               {"clojure", "blue"},
			".cfc":               {"coldfusion", "blue"},
			".cfm":               {"coldfusion", "blue"},
			".coffee":            {"coffee", "yellow"},
			".litcoffee":         {"coffee", "yellow"},
			".config":            {"config", "grey-light"},
			".cfg":               {"config", "grey-light"},
			".conf":              {"config", "grey-light"},
			".cr":                {"crystal", "white"},
			".ecr":               {"crystal_embedded", "white"},
			".slang":             {"crystal_embedded", "white"},
			".cson":              {"json", "yellow"},
			".css":               {"css", "ignore"},
			".css.map":           {"css", "blue"},
			".sss":               {"css", "blue"},
			".csv":               {"csv", "green"},
			".xsl":               {"csv", "green"},
			".xslt":              {"csv", "green"},
			".text":              {"text", "ignore"},
			".log":               {"file-history", "ignore"},
			".webmanifest":       {"w3c", "blue"},
			".binary":            {"binary", "green"},
			".octet":             {"binary", "blue"},
			".ocsp-response":     {"binary", "ignore"},
			".protobuf":          {"protobuf", "green"},
			".xls":               {"xls", "green"},
			".xlsx":              {"xls", "green"},
			".cake":              {"cake", "red"},
			".ctp":               {"cake_php", "red"},
			".d":                 {"d", "red"},
			".doc":               {"word", "blue"},
			".docx":              {"word", "blue"},
			".ejs":               {"ejs", "yellow"},
			".ex":                {"elixir", "purple"},
			".exs":               {"elixir_script", "purple"},
			".elm":               {"elm", "blue"},
			".ico":               {"image", "ignore"},
			".fs":                {"f-sharp", "blue"},
			".fsx":               {"f-sharp", "blue"},
			".gitignore":         {"git", "ignore"},
			".gitconfig":         {"git", "ignore"},
			".gitkeep":           {"git", "ignore"},
			".gitattributes":     {"git", "ignore"},
			".gitmodules":        {"git", "ignore"},
			".go":                {"go2", "blue"},
			".slide":             {"go", "blue"},
			".article":           {"go", "blue"},
			".gradle":            {"gradle", "green"},
			".groovy":            {"grails", "green"},
			".gsp":               {"grails", "green"},
			".gql":               {"graphql", "pink"},
			".graphql":           {"graphql", "pink"},
			".haml":              {"haml", "red"},
			".handlebars":        {"mustache", "orange"},
			".hbs":               {"mustache", "orange"},
			".hjs":               {"mustache", "orange"},
			".hs":                {"haskell", "purple"},
			".lhs":               {"haskell", "purple"},
			".hx":                {"haxe", "orange"},
			".hxs":               {"haxe", "yellow"},
			".hxp":               {"haxe", "blue"},
			".hxml":              {"haxe", "purple"},
			".xhtml":             {"html", "purple"},
			".html":              {"html", "orange"},
			".htm":               {"html", "orange"},
			".jade":              {"jade", "red"},
			".java":              {"java", "red"},
			".class":             {"java", "red"},
			".classpath":         {"java", "red"},
			".properties":        {"java", "red"},
			".js":                {"js", "yellow"},
			".js.gz":             {"js", "yellow"},
			".js.map":            {"js", "yellow"},
			".spec.js":           {"js", "orange"},
			".test.js":           {"js", "orange"},
			".es":                {"js", "yellow"},
			".es5":               {"js", "yellow"},
			".es6":               {"js", "yellow"},
			".es7":               {"js", "yellow"},
			".jinja":             {"jinja", "red"},
			".jinja2":            {"jinja", "red"},
			".json":              {"json", "lightyellow"},
			".jl":                {"julia", "purple"},
			".kt":                {"kotlin", "orange"},
			".kts":               {"kotlin", "orange"},
			".dart":              {"dart", "blue"},
			".less":              {"less", "blue"},
			".liquid":            {"liquid", "green"},
			".ls":                {"livescript", "blue"},
			".lua":               {"lua", "blue"},
			".markdown":          {"markdown", "blue"},
			".md":                {"markdown", "blue"},
			".argdown":           {"argdown", "blue"},
			".ad":                {"argdown", "blue"},
			".mustache":          {"mustache", "orange"},
			".stache":            {"mustache", "orange"},
			".njk":               {"nunjucks", "green"},
			".nunjucks":          {"nunjucks", "green"},
			".nunjs":             {"nunjucks", "green"},
			".nunj":              {"nunjucks", "green"},
			".njs":               {"nunjucks", "green"},
			".nj":                {"nunjucks", "green"},
			".npm-debug.log":     {"npm", "ignore"},
			".npmignore":         {"npm", "red"},
			".npmrc":             {"npm", "red"},
			".ml":                {"ocaml", "orange"},
			".mli":               {"ocaml", "orange"},
			".cmx":               {"ocaml", "orange"},
			".cmxa":              {"ocaml", "orange"},
			".odata":             {"odata", "orange"},
			".pl":                {"perl", "blue"},
			".php":               {"php", "violet"},
			".php.inc":           {"php", "violet"},
			".pddl":              {"pddl", "purple"},
			".plan":              {"plan", "green"},
			".happenings":        {"happenings", "blue"},
			".ps1":               {"powershell", "blue"},
			".psd1":              {"powershell", "blue"},
			".psm1":              {"powershell", "blue"},
			".pug":               {"pug", "red"},
			".pp":                {"puppet", "yellow"},
			".epp":               {"puppet", "yellow"},
			".py":                {"python", "blue"},
			".jsx":               {"react", "blue"},
			".spec.jsx":          {"react", "orange"},
			".test.jsx":          {"react", "orange"},
			".cjsx":              {"react", "blue"},
			".tsx":               {"react", "blue"},
			".spec.tsx":          {"react", "yellow"},
			".test.tsx":          {"react", "yellow"},
			".re":                {"reasonml", "red"},
			".R":                 {"R", "blue"},
			".rmd":               {"default", "blue"},
			".rb":                {"ruby", "red"},
			".erb":               {"html_erb", "red"},
			".erb.html":          {"html_erb", "red"},
			".html.erb":          {"html_erb", "red"},
			".rs":                {"rust", "grey-light"},
			".sass":              {"sass", "pink"},
			".scss":              {"sass", "pink"},
			".springBeans":       {"spring", "green"},
			".slim":              {"slim", "orange"},
			".smarty.tpl":        {"smarty", "yellow"},
			".sbt":               {"sbt", "blue"},
			".scala":             {"scala", "red"},
			".sol":               {"ethereum", "blue"},
			".styl":              {"stylus", "green"},
			".swift":             {"swift", "orange"},
			".sql":               {"db", "pink"},
			".tf":                {"terraform", "purple"},
			".tf.json":           {"terraform", "purple"},
			".tfvars":            {"terraform", "purple"},
			".tex":               {"tex", "blue"},
			".sty":               {"tex", "yellow"},
			".dtx":               {"tex", "orange"},
			".ins":               {"tex", "white"},
			".txt":               {"doc", "white"},
			".other":             {"doc", "grey"},
			".pem":               {"binary", "green"},
			".toml":              {"config", "grey-light"},
			".twig":              {"twig", "green"},
			".ts":                {"typescript", "blue"},
			".spec.ts":           {"typescript", "yellow"},
			".test.ts":           {"typescript", "yellow"},
			".vala":              {"vala", "grey-light"},
			".vapi":              {"vala", "grey-light"},
			".vue":               {"vue", "green"},
			".wasm":              {"wasm", "purple"},
			".wat":               {"wat", "purple"},
			".xml":               {"xml", "orange"},
			".yml":               {"yml", "purple"},
			".yaml":              {"yml", "purple"},
			".pro":               {"prolog", "orange"},
			".jar":               {"zip", "grey-light"},
			".rar":               {"zip", "grey-light"},
			".zip":               {"zip", "grey-light"},
			".tar.gz":            {"zip", "grey-light"},
			".tar.bz2":           {"zip", "grey-light"},
			".tgz":               {"zip", "grey-light"},
			".tar":               {"zip", "grey-light"},
			".7z":                {"zip", "grey-light"},
			".gz":                {"zip", "grey-light"},
			".backup":            {"zip", "grey-light"},
			".wgt":               {"wgt", "blue"},
			".ai":                {"illustrator", "yellow"},
			".psd":               {"photoshop", "blue"},
			".pdf":               {"pdf", "red"},
			".eot":               {"font", "red"},
			".ttf":               {"font", "red"},
			".otf":               {"font", "red"},
			".woff":              {"font", "red"},
			".woff2":             {"font", "red"},
			".gif":               {"image", "ignore"},
			".webp":              {"image", "ignore"},
			".jpg":               {"image", "ignore"},
			".jpeg":              {"image", "ignore"},
			".png":               {"image", "ignore"},
			".pxm":               {"image", "ignore"},
			".svg":               {"svg", "ignore"},
			".svgx":              {"image", "ignore"},
			".sublime-project":   {"sublime", "orange"},
			".sublime-workspace": {"sublime", "orange"},
			".code-search":       {"code-search", "purple"},
			".component":         {"salesforce", "blue"},
			".cls":               {"salesforce", "blue"},
			".sh":                {"shell", "grey"},
			".zsh":               {"shell", "grey"},
			".fish":              {"shell", "grey"},
			".zshrc":             {"shell", "grey"},
			".bashrc":            {"shell", "grey"},
			".bash_profile":      {"shell", "grey"},
			".bash_aliases":      {"shell", "grey"},
			".bash_history":      {"shell", "grey"},
			".bash_logout":       {"shell", "grey"},
			".bash_prompt":       {"shell", "grey"},
			".mov":               {"video", "pink"},
			".ogv":               {"video", "pink"},
			".webm":              {"video", "pink"},
			".avi":               {"video", "pink"},
			".mpg":               {"video", "pink"},
			".mp4":               {"video", "pink"},
			".mp3":               {"audio", "purple"},
			".ogg":               {"audio", "purple"},
			".wav":               {"audio", "purple"},
			".flac":              {"audio", "purple"},
			".3ds":               {"svg", "blue"},
			".3dm":               {"svg", "blue"},
			".stl":               {"svg", "blue"},
			".obj":               {"svg", "blue"},
			".dae":               {"svg", "blue"},
			".bat":               {"windows", "blue"},
			".cmd":               {"windows", "blue"},
			".babelrc":           {"babel", "yellow"},
			".babelrc.js":        {"babel", "yellow"},
			".babelrc.cjs":       {"babel", "yellow"},
			".bowerrc":           {"bower", "orange"},
			".codeclimate.yml":   {"code-climate", "green"},
			".eslintrc":          {"eslint", "purple"},
			".eslintrc.js":       {"eslint", "purple"},
			".eslintrc.yaml":     {"eslint", "purple"},
			".eslintrc.yml":      {"eslint", "purple"},
			".eslintrc.json":     {"eslint", "purple"},
			".eslintignore":      {"eslint", "grey"},
			".firebaserc":        {"firebase", "orange"},
			".jshintrc":          {"js", "blue"},
			".jscsrc":            {"js", "blue"},
			".stylelintrc":       {"stylelint", "white"},
			".stylelintrc.json":  {"stylelint", "white"},
			".stylelintrc.yaml":  {"stylelint", "white"},
			".stylelintrc.yml":   {"stylelint", "white"},
			".stylelintrc.js":    {"stylelint", "white"},
			".stylelintignore":   {"stylelint", "grey"},
			".direnv":            {"config", "grey-light"},
			".env":               {"config", "grey-light"},
			".static":            {"config", "grey-light"},
			".editorconfig":      {"config", "grey-light"},
			".slugignore":        {"config", "grey-light"},
			".tmp":               {"clock", "grey-light"},
			".htaccess":          {"config", "grey-light"},
			".key":               {"lock", "green"},
			".cert":              {"lock", "green"},
			".crt":               {"lock", "green"},
			".DS_Store":          {"ignored", "ignore"},
		},
	}

}
